export const captions = [
  "Smiling moment",
  "Quiet afternoon walk",
  "Old stone pathway",
  "Sunset over the hills",
  "Crowded city street",
  "Calm forest trail",
  "Historic building view",
  "Traveler on the move",
  "Soft morning light",
  "Peaceful river bend",
  "Modern skyline",
  "Warm human connection",
  "Narrow alleyway",
  "Cliffside adventure",
  "Quiet lakeside scene",
  "Friendly face",
  "Bold architectural lines",
  "Winding mountain road",
  "Light through the trees",
  "Busy marketplace",
  "Silent snowy path",
  "Hidden courtyard",
  "Open ocean horizon",
  "Vintage doorway",
  "Exploring new places",
  "Foggy morning view",
  "Old bridge crossing",
  "Golden hour portrait",
  "City life details",
  "Rocky coastline",
  "Flowing water stream",
  "Tall glass buildings",
  "Traveler’s pause",
  "Colorful street scene",
  "Path into the woods",
  "Ancient stone walls",
  "Warm sunlight glow",
  "Quiet bench moment",
  "Riverside reflections",
  "Grand staircase",
  "Nature’s textures",
  "Charming town street",
  "Cloudy mountain peak",
  "Bright city lights",
  "Relaxed outdoor moment",
  "Forest canopy view",
  "Open desert road",
  "Modern interior space",
  "Rustic wooden fence",
  "Windy coastline walk",
  "Chill moment in nature",
  "Peaceful architecture",
  "Small travel discovery",
  "Wide open landscape",
];
